### ISSUE TITLE
None of the matchings are working from the tutorial. 

### ISSUE THREAD

**Issue by Thiago-Alckmin** [cjerzak/LinkIt-software#4] opened 2024-07-01 07:55 UTC
Hello, 

I am coauthoring a paper which would really benefit from your package as it leverages data from LinkedIn. Part of the project requires that we map individual's firms from LinkedIn to their actual firms. 

I have attempted to implement your tutorial to test out the package and none of the matchings, not even the fuzzy matching, are working. I have all of the required packages installed and am connected to the internet. The error message that is sent is: "Index out of bounds" (in Portuguese). I've attached the log file here. I am running this on Windows 11. 

I have tried tracing back the issue but came out empty handed. 

Could you please shine a light on whether you have encountered this issue before and steps I can take to improve it? 

Thank you in advance!
Thiago

```
>   # clear workspace
Warning message:
replacing previous import ‘Rfast::transpose’ by ‘data.table::transpose’ when loading ‘LinkOrgs’ 
>   rm( list = ls())
>   # Load package
>   library( LinkOrgs )
>   # Create synthetic data to try package out
>   x <- data.frame("orgnames_x" = x_orgnames <- c("apple","oracle",
+                                                  "enron inc.","mcdonalds corporation"))
>   y <- data.frame("orgnames_y"= y_orgnames <- c("apple corp","oracle inc",
+                                                 "enron","mcdonalds co"))
>   # Perform a merge using parallelized fuzzy matching
>   LinkedOrgs_fuzzy <- LinkOrgs(x = x, by.x = "orgnames_x",
+                                y = y, by.y = "orgnames_y",
+                                algorithm = "fuzzy")
[1] "[2024-07-01 14:43:27] Pre-processing strings..."
[1] "[2024-07-01 14:43:27] Searching for matches in the raw name space..."
[1] "[2024-07-01 14:43:27] Calibrating via AveMatchNumberPerAlias..."
[1] "[2024-07-01 14:43:32] Calibrated accept match dist threshold: 0.920000"
Error in { : task 2 failed - "índice fora de limites" 
Além disso: There were 11 warnings (use warnings() to see them)
> warnings()
Mensagens de aviso:
1: package ‘plyr’ was built under R version 4.2.3
2: package ‘dplyr’ was built under R version 4.2.3
3: package ‘data.table’ was built under R version 4.2.3
4: package ‘fastmatch’ was built under R version 4.2.3
5: package ‘stringdist’ was built under R version 4.2.3
6: package ‘stringr’ was built under R version 4.2.3
7: package ‘foreach’ was built under R version 4.2.3
8: package ‘doParallel’ was built under R version 4.2.3
9: package ‘iterators’ was built under R version 4.2.3
10: In e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): split_list_x, DistanceMeasure, qgram, nCores, ReturnProgress, x_tri_index, y_tri_index, MaxDist, x, by.x, y, by.y
11: In e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): split_list_x, DistanceMeasure, qgram, nCores, ReturnProgress, x_tri_index, y_tri_index, MaxDist, x, by.x, y, by.y

```

**Comment by beniaminogreen** [comment] 2024-07-01 14:57
Thanks for flagging this. I am not a package author so I might have trouble rooting this issue out, but I'll try and see if I can diagnose + provide a fix.  I also can confirm that I can reproduce this error on my computer, and to provide a [reprex](https://reprex.tidyverse.org/l) w/ my session info.

``` 
x_orgnames <- c("apple","oracle","enron inc.","mcdonalds corporation")
y_orgnames <- c("apple corp","oracle inc","enron","mcdonalds")
x <- data.frame("orgnames_x"=x_orgnames)
y <- data.frame("orgnames_y"=y_orgnames)
zz_linked_fuzzy <- LinkOrgs::LinkOrgs(x  = x,
                        y =  y,
                        by.x = "orgnames_x",
                        by.y = "orgnames_y",
                        algorithm = "fuzzy",
                        DistanceMeasure = "jaccard",
                        AveMatchNumberPerAlias = 1)
#> Warning: replacing previous import 'Rfast::transpose' by
#> 'data.table::transpose' when loading 'LinkOrgs'
#> [1] "[2024-07-01 10:48:49] Pre-processing strings..."
#> [1] "[2024-07-01 10:48:49] Searching for matches in the raw name space..."
#> [1] "[2024-07-01 10:48:49] Calibrating via AveMatchNumberPerAlias..."
#> Warning in e$fun(obj, substitute(ex), parent.frame(), e$data): already
#> exporting variable(s): split_list_x, DistanceMeasure, qgram, nCores,
#> ReturnProgress, x_tri_index, y_tri_index, MaxDist, x, by.x, y, by.y
#> [1] "[2024-07-01 10:48:51] Calibrated accept match dist threshold: 0.527778"
#> Warning in e$fun(obj, substitute(ex), parent.frame(), e$data): already
#> exporting variable(s): split_list_x, DistanceMeasure, qgram, nCores,
#> ReturnProgress, x_tri_index, y_tri_index, MaxDist, x, by.x, y, by.y
#> Error in {: task 2 failed - "subscript out of bounds"
```

<sup>Created on 2024-07-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.2 (2023-10-31)
#>  os       NixOS 23.11 (Tapir)
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/New_York
#>  date     2024-07-01
#>  pandoc   3.1.9 @ /run/current-system/sw/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version date (UTC) lib   source
#>  cli            3.6.1   2023-03-23 [18]  CRAN (R 4.3.2)
#>  codetools      0.2-19  2023-02-01 [6]   CRAN (R 4.3.2)
#>  data.table   * 1.14.8  2023-02-17 [128] CRAN (R 4.3.2)
#>  digest         0.6.33  2023-07-07 [33]  CRAN (R 4.3.2)
#>  doParallel   * 1.0.17  2022-02-07 [133] CRAN (R 4.3.2)
#>  dplyr        * 1.1.3   2023-09-03 [130] CRAN (R 4.3.2)
#>  evaluate       0.22    2023-09-29 [60]  CRAN (R 4.3.2)
#>  fansi          1.0.5   2023-10-08 [61]  CRAN (R 4.3.2)
#>  fastmap        1.1.1   2023-02-24 [29]  CRAN (R 4.3.2)
#>  fastmatch    * 1.1-4   2023-08-18 [123] CRAN (R 4.3.2)
#>  foreach      * 1.5.2   2022-02-02 [119] CRAN (R 4.3.2)
#>  fs             1.6.3   2023-07-20 [24]  CRAN (R 4.3.2)
#>  generics       0.1.3   2022-07-05 [131] CRAN (R 4.3.2)
#>  glue           1.6.2   2022-02-24 [26]  CRAN (R 4.3.2)
#>  htmltools      0.5.6.1 2023-10-06 [31]  CRAN (R 4.3.2)
#>  iterators    * 1.0.14  2022-02-05 [120] CRAN (R 4.3.2)
#>  jsonlite       1.8.7   2023-06-29 [37]  CRAN (R 4.3.2)
#>  knitr          1.44    2023-09-11 [75]  CRAN (R 4.3.2)
#>  lattice        0.22-4  2023-10-22 [9]   CRAN (R 4.3.2)
#>  lifecycle      1.0.3   2022-10-07 [25]  CRAN (R 4.3.2)
#>  LinkOrgs       0.01    2024-07-01 [1]   Github (cjerzak/LinkOrgs-software@43fe082)
#>  magrittr       2.0.3   2022-03-30 [48]  CRAN (R 4.3.2)
#>  Matrix         1.6-1.1 2023-09-18 [10]  CRAN (R 4.3.2)
#>  nvimcom      * 0.9.33  2024-06-18 [1]   local
#>  pillar         1.9.0   2023-03-22 [82]  CRAN (R 4.3.2)
#>  pkgconfig      2.0.3   2019-09-22 [84]  CRAN (R 4.3.2)
#>  plyr         * 1.8.9   2023-10-02 [129] CRAN (R 4.3.2)
#>  png            0.1-8   2022-11-29 [126] CRAN (R 4.3.2)
#>  purrr          1.0.2   2023-08-10 [69]  CRAN (R 4.3.2)
#>  R.cache        0.16.0  2022-07-21 [143] CRAN (R 4.3.2)
#>  R.methodsS3    1.8.2   2022-06-13 [1]   CRAN (R 4.3.2)
#>  R.oo           1.26.0  2024-01-24 [1]   CRAN (R 4.3.2)
#>  R.utils        2.12.3  2023-11-18 [1]   CRAN (R 4.3.2)
#>  R6             2.5.1   2021-08-19 [20]  CRAN (R 4.3.2)
#>  Rcpp           1.0.11  2023-07-06 [46]  CRAN (R 4.3.2)
#>  RcppZiggurat   0.1.6   2020-10-20 [115] CRAN (R 4.3.2)
#>  reprex         2.1.0   2024-01-11 [1]   CRAN (R 4.3.2)
#>  reticulate     1.34.0  2023-10-12 [124] CRAN (R 4.3.2)
#>  Rfast          2.0.8   2023-07-03 [113] CRAN (R 4.3.2)
#>  rlang          1.1.1   2023-04-28 [23]  CRAN (R 4.3.2)
#>  rmarkdown      2.25    2023-09-18 [74]  CRAN (R 4.3.2)
#>  sessioninfo    1.2.2   2021-12-06 [91]  CRAN (R 4.3.2)
#>  stringdist   * 0.9.10  2022-11-07 [117] CRAN (R 4.3.2)
#>  stringi        1.7.12  2023-01-11 [79]  CRAN (R 4.3.2)
#>  stringr      * 1.5.0   2022-12-02 [78]  CRAN (R 4.3.2)
#>  styler         1.10.2  2023-08-29 [142] CRAN (R 4.3.2)
#>  tibble         3.2.1   2023-03-20 [81]  CRAN (R 4.3.2)
#>  tidyselect     1.2.0   2022-10-10 [132] CRAN (R 4.3.2)
#>  utf8           1.2.4   2023-10-22 [83]  CRAN (R 4.3.2)
#>  vctrs          0.6.4   2023-10-12 [62]  CRAN (R 4.3.2)
#>  withr          2.5.1   2023-09-26 [50]  CRAN (R 4.3.2)
#>  xfun           0.40    2023-08-09 [77]  CRAN (R 4.3.2)
#>  yaml           2.3.7   2023-01-23 [63]  CRAN (R 4.3.2)
#> 
#>  [1] /home/beniamino/LinkOrgs-software/LinkOrgs/_libs
#>  [2] /nix/store/p9f7nlj5w8azg0s14pfgfcbpxjwz0dbk-r-boot-1.3-28.1/library
#>  [3] /nix/store/80j99ckck93pbr2l9mlyhg5lc5b4y7i8-r-class-7.3-22/library
#>  [4] /nix/store/4azrp9y3gsapa9j5kb5973yswrqbdv5d-r-MASS-7.3-60/library
#>  [5] /nix/store/sciaagk8brx67y7cfh7rhk1pp2n09qas-r-cluster-2.1.4/library
#>  [6] /nix/store/vfvlgbwg1f3mzzc8pwra0fndw5scj3fd-r-codetools-0.2-19/library
#>  [7] /nix/store/jrlb2k9f3cc5g654ph33nyc14lg6i47v-r-foreign-0.8-85/library
#>  [8] /nix/store/h11a9ih2r0q11iddin4xgwcdd231j1r9-r-KernSmooth-2.23-22/library
#>  [9] /nix/store/xb8h2bypl14gd8iqlm8234aq4mssl09z-r-lattice-0.22-4/library
#>  [10] /nix/store/yfg0ghbbk9sadbpgaj3bzcpchikyf0yh-r-Matrix-1.6-1.1/library
#>  [11] /nix/store/1b4r68mf4jkra629sfgdxwfggbqdclzm-r-mgcv-1.9-0/library
#>  [12] /nix/store/iczyhrfp2608d5yay07xsss23hs5jm59-r-nlme-3.1-163/library
#>  [13] /nix/store/cwhqyags6xann20baylyxs64q8ap1fl2-r-nnet-7.3-19/library
#>  [14] /nix/store/b56g1s5ibznhhs4pn8dlyavblxcgzs16-r-rpart-4.1.21/library
#>  [15] /nix/store/ii1mwd0rhh0b7qmqk4spwsgidr9zhgps-r-spatial-7.3-17/library
#>  [16] /nix/store/ja28ssq2wfgspirrfdzyysqisc2cw9yk-r-survival-3.5-7/library
#>  [17] /nix/store/4lj0lc3p2kfqa74qw5h9jjyy55l13clc-r-devtools-2.4.5/library
#>  [18] /nix/store/sy851wlw2iahjkag3nlj9q28xvfmdky6-r-cli-3.6.1/library
#>  [19] /nix/store/hm9xl6qfisspb8pqzsmfllw75jm46pc0-r-desc-1.4.2/library
#>  [20] /nix/store/z5q2y18p1kzv33dfwmhi4ymhg4lm9qip-r-R6-2.5.1/library
#>  [21] /nix/store/nszl298h9wwb3b7p1dk96pwcg2csbkp1-r-rprojroot-2.0.3/library
#>  [22] /nix/store/fbzh8n1l90bn1xd13xzjgj4ilwi98lxa-r-ellipsis-0.3.2/library
#>  [23] /nix/store/86mjfmg79qpd1c6ydnjpilfcljawhp76-r-rlang-1.1.1/library
#>  [24] /nix/store/arwxlxygjlz5mvk04hy94bfqc7s4vbl8-r-fs-1.6.3/library
#>  [25] /nix/store/6c9ibj5xzlpjng4m5967m9nzpzx0ww6b-r-lifecycle-1.0.3/library
#>  [26] /nix/store/29j4pxxjz0z1j5i5iq5s6s114y92923w-r-glue-1.6.2/library
#>  [27] /nix/store/r3g01w1sszd39nqmf5437xqrh93xpdis-r-memoise-2.0.1/library
#>  [28] /nix/store/x6vq0nz7hyv51wpja3wsg0j28vgw7gdw-r-cachem-1.0.8/library
#>  [29] /nix/store/j2kjqr5xs1ch3kgaymwswcxq0mrvm21z-r-fastmap-1.1.1/library
#>  [30] /nix/store/w49w99cvc32a0n8dkqi2d4ckmkqgdg9f-r-miniUI-0.1.1.1/library
#>  [31] /nix/store/022wanzj3msq7j7gysyq1pka2i7aknz4-r-htmltools-0.5.6.1/library
#>  [32] /nix/store/32wrimpmxmcpwhab1iz2k7822vmr7ink-r-base64enc-0.1-3/library
#>  [33] /nix/store/0c6dysgz62x64r3siixaqix2i25bagir-r-digest-0.6.33/library
#>  [34] /nix/store/0zgljzap3wrmk04s2r3m3sbmgp0ngd0g-r-shiny-1.7.5.1/library
#>  [35] /nix/store/xbq9sjp37g5bab0i2x60aqy4naqx6glr-r-bslib-0.5.1/library
#>  [36] /nix/store/1mkjfj0rdca0kkqsmja8zk82d3l30v1p-r-jquerylib-0.1.4/library
#>  [37] /nix/store/cyqdqh7jfn3cx0rfkv8kbsypq4gklp9c-r-jsonlite-1.8.7/library
#>  [38] /nix/store/5fq94mi7q28rw6lk1a9gnsna04vasp68-r-mime-0.12/library
#>  [39] /nix/store/gyi9m107h8vhq61zlaafy9l2ksa3bwld-r-sass-0.4.7/library
#>  [40] /nix/store/v96z62qgn4g8kccbhln61p7qzhg3lr82-r-rappdirs-0.3.3/library
#>  [41] /nix/store/vxf4mcalynzc0cl8phq2fd4b8cw7x7fb-r-commonmark-1.9.0/library
#>  [42] /nix/store/03vylpq68qqyc28xdhfzym8dr0dcrkz5-r-crayon-1.5.2/library
#>  [43] /nix/store/7710m9qabymp1mjqsgr57bh6wc4vyxij-r-fontawesome-0.5.2/library
#>  [44] /nix/store/lf52vcrwgk0li52mqpphy15bg77qvq0c-r-httpuv-1.6.12/library
#>  [45] /nix/store/7hnahs2gjdax87kwqj5xvk8np68lhi0b-r-later-1.3.1/library
#>  [46] /nix/store/pk9d1cnm37z4f3m88h5x9k2idvs1r3b9-r-Rcpp-1.0.11/library
#>  [47] /nix/store/gc6x5mnp4fzll7balyh4fab7x79w3wi2-r-promises-1.2.1/library
#>  [48] /nix/store/fpcjiaynq3r6xa03y6306wr1nvbihh7y-r-magrittr-2.0.3/library
#>  [49] /nix/store/9scjrzcy963k5wiygj9pp41axcx25pl8-r-sourcetools-0.1.7-1/library
#>  [50] /nix/store/2000wpsr6ch6k6p07cjr6gm91a2xkghh-r-withr-2.5.1/library
#>  [51] /nix/store/g8b7iz8hvnkbm52qya7niflk2pa5xwdb-r-xtable-1.8-4/library
#>  [52] /nix/store/1jblsryy814mfppd9f3pkp1ba1wcnxxw-r-pkgbuild-1.4.2/library
#>  [53] /nix/store/13kin4nisw63vinfps4vh4cq05v901r5-r-callr-3.7.3/library
#>  [54] /nix/store/11776nsa1hrxnh4qsbqcx93pf4sa38gi-r-processx-3.8.2/library
#>  [55] /nix/store/0xw7j6z50xf11af44z2j4a36jg6injwj-r-ps-1.7.5/library
#>  [56] /nix/store/akp7w74ncrhaw2jniyxms4naj2fm9qri-r-prettyunits-1.2.0/library
#>  [57] /nix/store/jwwngapcv1680lhvzrj4g73vz7z7m70a-r-pkgdown-2.0.7/library
#>  [58] /nix/store/1rps72hw83797pp7c2h6wjahmh85flig-r-downlit-0.4.3/library
#>  [59] /nix/store/00c4ijlj4rlv1d9gm6m8fjx75id749yc-r-brio-1.1.3/library
#>  [60] /nix/store/rr70ix9jhy0wq9hmai1jr3y3i74bi94b-r-evaluate-0.22/library
#>  [61] /nix/store/hiqazchinwzp033ng4iz4q00880cmjqj-r-fansi-1.0.5/library
#>  [62] /nix/store/69i2df3m1jzza4ilpppj10sbqji2jvss-r-vctrs-0.6.4/library
#>  [63] /nix/store/z84agf6fsc4gkacng5fpgd97sj2ci42h-r-yaml-2.3.7/library
#>  [64] /nix/store/prkixr16vghhjrxqhhbfrhxxww61ll6z-r-httr-1.4.7/library
#>  [65] /nix/store/8qskz2cgaaam56r2ffs3n7xz7f0k7b38-r-curl-5.1.0/library
#>  [66] /nix/store/9p4a87w5q0fwwiz0969sx9ih4mpfxgdp-r-openssl-2.1.1/library
#>  [67] /nix/store/9w6gkxvyka02xqzk7vcswdjhkc676059-r-askpass-1.2.0/library
#>  [68] /nix/store/qgpav872w77gpfwcld67dxmq0vjcclvy-r-sys-3.4.2/library
#>  [69] /nix/store/nzxb2pnk4cy4s9d7v8wvjqpfjll876a4-r-purrr-1.0.2/library
#>  [70] /nix/store/j9ss9qcwmgmg45ijk5a0i78xn2z8jb12-r-ragg-1.2.6/library
#>  [71] /nix/store/xa7cz3zmffrn2zdlp69b82h9qa23szl2-r-systemfonts-1.0.5/library
#>  [72] /nix/store/84cqwxhm004v3f2bgrjxpqkp94mjyn53-r-cpp11-0.4.6/library
#>  [73] /nix/store/3sq5g7pgs1f0knxnd3z85zxak65d1vhn-r-textshaping-0.3.7/library
#>  [74] /nix/store/11c1npjghd7dn8vg0bhb4baqbqd97jcv-r-rmarkdown-2.25/library
#>  [75] /nix/store/82fc2f8kp3q2vdmjy24gfcn965v14r5y-r-knitr-1.44/library
#>  [76] /nix/store/69n7b6sjkjsrfjb5nb3al9vfv8a4mlc8-r-highr-0.10/library
#>  [77] /nix/store/aiwr0r9xgdclq1n1z4nqi4s28ckrzwx7-r-xfun-0.40/library
#>  [78] /nix/store/q47d0rkarzb0ac302hhcidzjqsyvp5xn-r-stringr-1.5.0/library
#>  [79] /nix/store/r8a1nb9sgvsp6ihkx3z66ngaiwizk0pb-r-stringi-1.7.12/library
#>  [80] /nix/store/m4mfm7dziqv83l3qwjl9h974w7580j1n-r-tinytex-0.48/library
#>  [81] /nix/store/w83a1crsc8f0zq3m57zqqjpl9f7b546p-r-tibble-3.2.1/library
#>  [82] /nix/store/mkf1hbmgpc83b9fxn5p9h6mqdm3cyafg-r-pillar-1.9.0/library
#>  [83] /nix/store/7cdldl136ds3ck0gc7b07l6w1kiin3x9-r-utf8-1.2.4/library
#>  [84] /nix/store/yl797b996kmwbxv1jp6rllji5nawbhv2-r-pkgconfig-2.0.3/library
#>  [85] /nix/store/2jbman4yzmlgdgcqlnwcpnrp2np72h9n-r-whisker-0.4.1/library
#>  [86] /nix/store/ai1rifl9b98q0pk6zwbkjbvwyjw9i6ml-r-xml2-1.3.5/library
#>  [87] /nix/store/3vnrfnxprdmjdyy34xsbwi6njh8bnab1-r-pkgload-1.3.3/library
#>  [88] /nix/store/jz4xailaqasgcmchs4kcybqbpnbxsn8h-r-profvis-0.3.8/library
#>  [89] /nix/store/a069k79jdp3ksbdrh6a3vwqchfqgdmbj-r-htmlwidgets-1.6.2/library
#>  [90] /nix/store/c79gz7sq3r86wcwppc5a0a8i7p0gdpg1-r-rcmdcheck-1.4.0/library
#>  [91] /nix/store/27pzwydlj0qqdryhqc8igbjgmvfb71w2-r-sessioninfo-1.2.2/library
#>  [92] /nix/store/6y9fn9yb9qpdiaf13hb9mbp7j2h0dxcf-r-xopen-1.0.0/library
#>  [93] /nix/store/n51pr4ilc6ag8120ngrwgya4fzvdqv6a-r-remotes-2.4.2.1/library
#>  [94] /nix/store/mbn1v0x37jhpncfrymc2kp3c3pr2y2z4-r-roxygen2-7.2.3/library
#>  [95] /nix/store/cs06cjgp3x1qzic1gwi5n788r8wdphsf-r-brew-1.0-8/library
#>  [96] /nix/store/anvhs6sbqdbz1mj7whxpmkk266c26mzr-r-rversions-2.1.2/library
#>  [97] /nix/store/ln6kcgr01lalv0ffa7il350vw2xfx66c-r-testthat-3.2.0/library
#>  [98] /nix/store/19mslyw8q8dysxzhmv12swma71whwmr2-r-praise-1.0.0/library
#>  [99] /nix/store/9if6nrlgnw548gkdgqgb8gcy0wnm01f3-r-waldo-0.5.1/library
#>  [100] /nix/store/xqx232bwq4zvsqnwdpysj4bmv1q4v6ay-r-diffobj-0.3.5/library
#>  [101] /nix/store/wwasxyxwrcfdrwz8ibrinz1awzhqviw6-r-rematch2-2.1.2/library
#>  [102] /nix/store/4xxmjp0473m017w99bagxv2ahnb64i62-r-urlchecker-1.0.1/library
#>  [103] /nix/store/kklmbmz9jrcclnxdvnbajlccab3vz5qc-r-usethis-2.2.2/library
#>  [104] /nix/store/rnk8nrdplk1i666bx7n5283n3kycsfmf-r-clipr-0.8.0/library
#>  [105] /nix/store/27jaw58c9jinxmyfcdlys3clp045z0v1-r-gert-2.0.0/library
#>  [106] /nix/store/n76jkvclhpibpwmaimna477di21fdx5z-r-credentials-2.0.1/library
#>  [107] /nix/store/93an7r9kz25sfpvvncgz9210vl2ymc67-r-rstudioapi-0.15.0/library
#>  [108] /nix/store/aqkgqjgbikckia5jqipjanrf6skh8ml6-r-zip-2.3.0/library
#>  [109] /nix/store/9mw5blb1a3fxcxcaf5x0hq13i7mpi44h-r-gh-1.4.0/library
#>  [110] /nix/store/3w1q6wgj38sf374r8p8csjwkwl9m9913-r-gitcreds-0.1.2/library
#>  [111] /nix/store/lqvir1n8wn7p8p73wjq1i68a8dz2k283-r-httr2-0.2.3/library
#>  [112] /nix/store/md5s2yxrg1rzqfyn7fgc4a60rri6hdnl-r-ini-0.3.1/library
#>  [113] /nix/store/1qmxcdgbgrm8n4b58pb966mvagbf4gp5-r-Rfast-2.0.8/library
#>  [114] /nix/store/wq1yh9l53wchq5f0ip2g3dila729mnag-r-RcppArmadillo-0.12.6.4.0/library
#>  [115] /nix/store/sm8vp1v5cyf07hhss02chpg1pj8djpdd-r-RcppZiggurat-0.1.6/library
#>  [116] /nix/store/gkk22vca4gb8hcyir597v2sskb481i8l-r-RcppGSL-0.3.13/library
#>  [117] /nix/store/ijv3dx8g1mxdciwgn8m9zlr263gwhmwf-r-stringdist-0.9.10/library
#>  [118] /nix/store/k0inp0iaifgm6dskjjqy5ia9vm2iyr56-r-glmnet-4.1-8/library
#>  [119] /nix/store/1ca6p7ydpf3w90gm2vxg6mb5yvvbl89i-r-foreach-1.5.2/library
#>  [120] /nix/store/ysffpc9f2dd2whkhklp7qicjmp09shm0-r-iterators-1.0.14/library
#>  [121] /nix/store/2ah1q0j921y4c39j6vymkmvaka99cy5z-r-RcppEigen-0.3.3.9.3/library
#>  [122] /nix/store/qzad3yhx6h51vanfmc3rr68ppiqxy904-r-shape-1.4.6/library
#>  [123] /nix/store/y0xh3cja3kzfca00jlr13rvncdkfiyfx-r-fastmatch-1.1-4/library
#>  [124] /nix/store/kyhalw6sx8zp7kjpg1mx7zf0h4w11143-r-reticulate-1.34.0/library
#>  [125] /nix/store/c7wzrcn353wl4w2zmffwdxpvm5vlk107-r-here-1.0.1/library
#>  [126] /nix/store/lc0gv0iidsc70qfkzwjvwkm226dpfr69-r-png-0.1-8/library
#>  [127] /nix/store/dr74m0033c7p1v046w2md95s9qac688z-r-RcppTOML-0.2.2/library
#>  [128] /nix/store/8h7s07mkk8c6qkvy6bhnwis4pcxmz6ld-r-data.table-1.14.8/library
#>  [129] /nix/store/i5720zjm6jj3clw32r5jnhfys5xr0dzr-r-plyr-1.8.9/library
#>  [130] /nix/store/bh9lnd1jzv553p5yxz7304iczpi3isyv-r-dplyr-1.1.3/library
#>  [131] /nix/store/sv462m1j52z4qv0p039isricsxbnxyxd-r-generics-0.1.3/library
#>  [132] /nix/store/vjc54k8kjf47f5ni65azy6anzrr4r0yd-r-tidyselect-1.2.0/library
#>  [133] /nix/store/rf4lxrsbdkjj4msdz2mx698b3jw0w6xf-r-doParallel-1.0.17/library
#>  [134] /nix/store/qaal2k8kf0rnvqv7r1hp44dnk1bss1zi-r-languageserver-0.3.16/library
#>  [135] /nix/store/5kmdws501bgg5b20q4navn87dp3k0m5z-r-collections-0.3.7/library
#>  [136] /nix/store/pjyp9if7mxndv0w8f21vqiwkf57f0pbl-r-lintr-3.1.0/library
#>  [137] /nix/store/icvliia5vg2cy7lp70wiyl5r3zd7mi20-r-backports-1.4.1/library
#>  [138] /nix/store/080cic453akvssn1wqk1fyj5wqlqdp1a-r-cyclocomp-1.1.1/library
#>  [139] /nix/store/5ng64h83v1ghxbbrwy0yqrmdcvg1l20m-r-rex-1.2.1/library
#>  [140] /nix/store/6an8mv48nnd10w3x7vj8l0104h0fvlrc-r-lazyeval-0.2.2/library
#>  [141] /nix/store/6vckc6z9zv0835q3zl6zq8sin1lqalnq-r-xmlparsedata-1.0.5/library
#>  [142] /nix/store/06h3awli51hcbmk84608i3iv0qcj2bhh-r-styler-1.10.2/library
#>  [143] /nix/store/7slgdmq9sfgl90h87fzqqbjqwxgd7dpq-r-R.cache-0.16.0/library
#>  [144] /nix/store/3h1nlgf27bcy1qgwir2q216p156sdbx0-r-R.methodsS3-1.8.2/library
#>  [145] /nix/store/02zs00a6igcl3i761s2h2nxqrlrsj7zv-r-R.oo-1.25.0/library
#>  [146] /nix/store/7hc9b7mdd81iqkgjp1zidw3jhlnsrwq0-r-R.utils-2.12.2/library
#>  [147] /nix/store/jd594jn7bv20qfwgnrj38nn92s2flqyd-R-4.3.2/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

In the future, I think it would be nice to set up some continuous integration so we will get an error if we try and push breaking changes to the main branch. The zoomerjoin branch currently has some unit tests, but these examples aren't yet tested.

**Comment by beniaminogreen** [comment] 2024-07-01 15:13
I just used [git bisect](https://git-scm.com/docs/git-bisect) to find when this bug was introduced, and it looks like this issue was introduced in 3d193d2630a91814efce02970ff37a66904b4e14. 

Also of note is that I tested commits 19a1c5e91fe71a51e94e2ba0baf7a619bb900518  and 9567534960a39e9c89c5530272537e1676288948 while bisecting and the code would hang forever without finishing.

**Comment by cjerzak** [comment] 2024-07-03 01:56
Thank you for pointing this out. Working on it now! I believe the issue is due to a the way we handled parallelization of the match calculations, which is problematic when the number of items to match is very small like in these tutorials. More soon.

**Comment by cjerzak** [comment] 2024-07-03 02:07
Thank you again @Thiago-Alckmin for pointing this out. 

I believe the tutorial code now should work with the latest version of the package. 

The issue was that for this very small example, the number of possible matches got close to the number of CPU cores available, so that some cores actually got no jobs to run, causing the bug. Thank you again and let us know if you run into anything else.

**Comment by cjerzak** [comment] 2024-07-03 15:54
Closing for now based on the prior discussion but feel free to re-open if the issue persists or others come up.

**Closed as completed by cjerzak** 2024-07-03 15:54 UTC
